services:
  - type: web
    name: jarvis-web
    env: python
    plan: free
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: GROQ_API_KEY
        value: "paste_groq_key_here"
      - key: GEMINI_API_KEY
        value: "paste_gemini_key_here"
